#!/bin/sh

function checkFileExisting () {
    if [ -e $1 ]; then
        echo "Already exists $1"
        exit 1
    fi
}

# echo $(dirname $0)
SCRIPT_DIR=`cd $(dirname ${BASH_SOURCE[0]}) && pwd`

checkFileExisting ~/.tmux.conf
checkFileExisting ~/.zshrc

cd ~ && ln -s ${SCRIPT_DIR}/.tmux.conf .tmux.conf
cd ~ && ln -s ${SCRIPT_DIR}/.zshrc .zshrc